
/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: "1",
    title: "Fall Guys: Ultimate Knockout",
    desc: "a massively 60 multiplayer game",
    categoryName: ["arcade-and-puzzle"],
    vendor: "mediatonic",
    price: "49.99",
    discount: "2",
    isLatest: true,
    isTop: true,
    rating: 4.2,
    imageSrc:
      "https://res.cloudinary.com/dmlhtqirp/image/upload/v1686415174/BRUKart/fall-guys.png",
  },
  {
    _id: "2",
    title: "BATTLEGROUNDS Mobile India",
    desc: "loot weapons and supplies, and survive among 100 players",
    categoryName: ["adventure", "action", "simulation"],
    vendor: "tencent",
    price: "89.99",
    discount: "4",
    isLatest: true,
    isTop: false,
    rating: 4.8,
    imageSrc:
      "https://res.cloudinary.com/dmlhtqirp/image/upload/v1686652620/BRUKart/bgmi-unban.png",
  },
  {
    _id: "3",
    title: "Crazy Taxi",
    desc: "drive crazy to the city and earn the respect in your city",
    categoryName: ["racing", "arcade-and-puzzle"],
    vendor: "Dreamcast Games",
    price: "39.99",
    discount: "20",
    isLatest: false,
    isTop: false,
    rating: 2.2,
    imageSrc:
      "https://res.cloudinary.com/dmlhtqirp/image/upload/v1686415138/BRUKart/crazy-taxi.jpg",
  },
  {
    _id: "4",
    title: "Resident Evil 4",
    desc: "xyz",
    categoryName: ["action", "adventure"],
    vendor: "xyz",
    price: "259.99",
    discount: "60",
    isLatest: true,
    isTop: false,
    rating: 4.4,
    imageSrc:
      "https://res.cloudinary.com/dmlhtqirp/image/upload/v1686415138/BRUKart/resident-evil-4.jpg",
  },
  {
    _id: "5",
    title: "Shadow of the Tomb Raider",
    desc: "As Lara Croft races to save the world from a Maya apocalypse, she must become the Tomb Raider she is destined to be",
    categoryName: ["action", "adventure"],
    vendor: "Square Enix",
    price: "59.99",
    discount: "72",
    isLatest: true,
    isTop: true,
    rating: 4.9,
    imageSrc:
      "https://res.cloudinary.com/dmlhtqirp/image/upload/v1686415138/BRUKart/shadow-of-the-tomb-raider.jpg",
  },
  {
    _id: "6",
    title: "Mini Militia - Doodle Army",
    desc: "It is a multiplayer game where you can battle with up to 6 players online or 12 players via LAN",
    categoryName: ["action"],
    vendor: "Appsomniacs LLC",
    price: "29.99",
    discount: "5",
    isLatest: false,
    isTop: false,
    rating: 3.9,
    imageSrc:
      "https://res.cloudinary.com/dmlhtqirp/image/upload/v1686415138/BRUKart/mini-militia.jpg",
  },
  {
    _id: "7",
    title: "Smash Karts",
    desc: "Drive your go-kart, pick up weapons, and blow up other karts to win! Keep playing to level up and unlock new characters and prizes",
    categoryName: ["action", "simulation"],
    vendor: "xyz",
    price: "60",
    discount: "10",
    isLatest: true,
    isTop: true,
    rating: 4.5,
    imageSrc:
      "https://res.cloudinary.com/dmlhtqirp/image/upload/v1686415139/BRUKart/smash-kart.jpg",
  },
  {
    _id: "8",
    title: "Among Us",
    desc: "party game of teamwork and betrayal",
    categoryName: ["action", "adventure"],
    vendor: "xyz",
    price: "78.99",
    discount: "30",
    isLatest: true,
    isTop: false,
    rating: 1.5,
    imageSrc:
      "https://res.cloudinary.com/dmlhtqirp/image/upload/v1686415172/BRUKart/among-us.jpg",
  },
  {
    _id: "9",
    title: "Asphalt 9: Legends",
    desc: "best arcade racing game",
    categoryName: ["racing", "adventure", "arcade"],
    vendor: "Gameloft",
    price: "68.99",
    discount: "15",
    isLatest: true,
    isTop: true,
    rating: 4.8,
    imageSrc:
      "https://res.cloudinary.com/dmlhtqirp/image/upload/v1686415139/BRUKart/asphalt-9-legends.jpg",
  },
  {
    _id: "10",
    title: "Trial Xtreme 4",
    desc: "race with time constraints on challenging terrains",
    categoryName: ["racing", "adventure"],
    vendor: "Deemedya INC",
    price: "59.99",
    discount: "15",
    isLatest: false,
    isTop: false,
    rating: 4.7,
    imageSrc:
      "https://res.cloudinary.com/dmlhtqirp/image/upload/v1686415139/BRUKart/trial-xtreme.jpg",
  },
  {
    _id: "11",
    title: "Balloon Blow",
    desc: "try to maintain balloon flow away from falling on horizon",
    categoryName: ["simulation", "arcade-and-puzzle"],
    vendor: "xyz",
    price: "49.99",
    discount: "10",
    isLatest: true,
    isTop: false,
    rating: 4.1,
    imageSrc:
      "https://res.cloudinary.com/dmlhtqirp/image/upload/v1686415138/BRUKart/balloon-blow.jpg",
  },
  {
    _id: "12",
    title: "Ball Blast",
    desc: "crush as many balls as possible from your canon and race the leaderboard",
    categoryName: ["action", "arcade-and-puzzle"],
    vendor: "xyz",
    price: "49.99",
    discount: "12",
    isLatest: true,
    isTop: true,
    rating: 4.4,
    imageSrc:
      "https://res.cloudinary.com/dmlhtqirp/image/upload/v1686415138/BRUKart/ball-blast.jpg",
  },
  {
    _id: "13",
    title: "Frontline Commando",
    desc: "survive amongst multiplayers with first-person-perspective",
    categoryName: ["action", "simulation", "adventure"],
    vendor: "xyz",
    price: "150",
    discount: "30",
    isLatest: true,
    isTop: true,
    rating: 4.4,
    imageSrc:
      "https://res.cloudinary.com/dmlhtqirp/image/upload/v1686514394/BRUKart/frontline-commando.jpg",
  },
];
